### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by dustinhughes**

### CODE REVIEW

**Comment by scottsauberlt** [comment]
Lots of flair ✨

**Comment by scottsauber** [comment]
Closing this PR. If you have any questions, let me know!

**Comment by dustinhughes** [comment]
Thanks, Scott.

I'm busy with your Dometrain course. I messed up somewhere—the pull request kept being created on your repo instead of my fork.

All good. Really enjoying the course!

All the best for 2025
Dustin

________________________________

**Comment by scottsauberlt** [comment]
@dustinhughes - if you want to change this to open to your fork instead of my base repo, take a look at this - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by dustinhughes** [comment]
Thanks, I'll check it out!

**Pull request closed without merging**
